name: Run Final Pipeline Script

on:
  push:
    branches:
      - cicd  # Trigger workflow on push to cicd branch

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: bilingualcomplaint-system

      - name: Create Service Account Key File
        # This step writes the GCP_SA_KEY secret to the correct file location.
        run: echo "${{ secrets.GCP_SA_KEY }}" > ${{ github.workspace }}/pipeline/all_in_one_service_account_key.json

      - name: Install dependencies
        run: |
          pip install -r pipeline/pipeline_requirements.txt

      - name: Run Final Pipeline Script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ github.workspace }}/pipeline/all_in_one_service_account_key.json"
        run: |
          python pipeline/final_pipeline.py
